# Generated by Django 3.1.5 on 2021-02-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='package',
        ),
    ]
