# Generated by Django 3.1.5 on 2021-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_robot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AddField(
            model_name='robot',
            name='x',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='y',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
    ]
