# Generated by Django 3.1.5 on 2021-02-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_package_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_package', models.BooleanField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='design.package')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='design.robot')),
            ],
        ),
    ]
