# Generated by Django 3.1.5 on 2021-02-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fifth_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='first_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='fourth_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='second_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='sixth_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='third_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='design.node'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='ending_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending', to='design.node'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='starting_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting', to='design.node'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='node',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='node',
            name='y_coordinate',
        ),
    ]
