# Generated by Django 3.1.5 on 2021-02-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20210224_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='x',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='y',
        ),
        migrations.AddField(
            model_name='robot',
            name='node_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_id', to='design.node'),
        ),
    ]
