# Generated by Django 3.1.5 on 2021-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_auto_20210225_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='node',
            name='sixth_node',
        ),
        migrations.RemoveField(
            model_name='package',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='height',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='name',
        ),
        migrations.AddField(
            model_name='node',
            name='fifth_node_distance',
            field=models.IntegerField(default=1, verbose_name='distance_to_fifth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='first_node_distance',
            field=models.IntegerField(default=1, verbose_name='distance_to_first'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='fourth_node_distance',
            field=models.IntegerField(default=1, verbose_name='distance_to_fourth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='second_node_distance',
            field=models.IntegerField(default=1, verbose_name='distance_to_second'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='third_node_distance',
            field=models.IntegerField(default=1, verbose_name='distance_to_third'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='compartment_size',
            field=models.IntegerField(default=1, verbose_name='Compartment_size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='id',
            field=models.AutoField(default=22, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='number_of_compartments',
            field=models.IntegerField(default=22, verbose_name='Compartments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
