# Generated by Django 3.1.5 on 2021-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_remove_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='fifth_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='distance_to_fifth'),
        ),
        migrations.AlterField(
            model_name='node',
            name='first_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='distance_to_first'),
        ),
        migrations.AlterField(
            model_name='node',
            name='fourth_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='distance_to_fourth'),
        ),
        migrations.AlterField(
            model_name='node',
            name='second_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='distance_to_second'),
        ),
        migrations.AlterField(
            model_name='node',
            name='third_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='distance_to_third'),
        ),
    ]
