# Generated by Django 3.1.5 on 2021-02-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_auto_20210225_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
    ]
