# Generated by Django 3.1.5 on 2021-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_remove_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='code',
            new_name='id',
        ),
        migrations.AddField(
            model_name='package',
            name='heigth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
