# Generated by Django 3.1.5 on 2021-02-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20210225_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Shelf', to='design.shelf'),
            preserve_default=False,
        ),
    ]
