# Generated by Django 3.1.5 on 2021-03-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_package_shelf_compartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='hidden_package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('shelf_compartment', models.IntegerField(blank=True, null=True, verbose_name='Compartment')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('heigth', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shelff', to='design.shelf')),
            ],
        ),
    ]
