# Generated by Django 3.1.5 on 2021-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_auto_20210301_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidden_package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
