# Generated by Django 3.1.5 on 2021-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20210301_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidden_package',
            name='old_id',
            field=models.IntegerField(default=1, verbose_name='old_id'),
            preserve_default=False,
        ),
    ]
