# Generated by Django 3.1.5 on 2021-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0021_hidden_package_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='robot',
        ),
        migrations.AddField(
            model_name='robot',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(default=1, max_length=120, primary_key=True, serialize=False, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
