# Generated by Django 3.1.5 on 2021-03-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_auto_20210308_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='ip',
        ),
    ]
