# Generated by Django 3.1.5 on 2021-03-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_remove_robot_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='design.robot'),
            preserve_default=False,
        ),
    ]
