# Generated by Django 3.1.5 on 2021-03-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_auto_20210308_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hidden_package',
            old_name='heigth',
            new_name='height',
        ),
    ]
