# Generated by Django 3.1.5 on 2021-03-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0026_auto_20210308_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='fifth_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='fifth_node_distance',
        ),
    ]
