# Generated by Django 3.1.5 on 2021-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0027_auto_20210314_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='right_node_direction',
            field=models.CharField(blank=True, choices=[('bi', 'bi'), ('from', 'from'), ('to', 'to')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='right_node_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
