# Generated by Django 3.1.5 on 2021-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0028_auto_20210314_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='first_node',
            new_name='right_node',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='first_node_distance',
            new_name='right_node_distance',
        ),
        migrations.AddField(
            model_name='node',
            name='down_node_direction',
            field=models.CharField(blank=True, choices=[('bi', 'bi'), ('from', 'from'), ('to', 'to')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='down_node_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='left_node_direction',
            field=models.CharField(blank=True, choices=[('bi', 'bi'), ('from', 'from'), ('to', 'to')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='left_node_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='up_node_direction',
            field=models.CharField(blank=True, choices=[('bi', 'bi'), ('from', 'from'), ('to', 'to')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='up_node_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
