# Generated by Django 3.1.5 on 2021-03-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0029_auto_20210314_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='second_node_distance',
            new_name='down_node_distance',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='third_node_distance',
            new_name='left_node_distance',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='fourth_node_distance',
            new_name='up_node_distance',
        ),
        migrations.RemoveField(
            model_name='node',
            name='fourth_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='second_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='third_node',
        ),
        migrations.AddField(
            model_name='node',
            name='down_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='left_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left', to='design.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='up_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up', to='design.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='right_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right', to='design.node'),
        ),
    ]
