# Generated by Django 3.1.5 on 2021-03-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0030_auto_20210314_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='down_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Down node distance'),
        ),
        migrations.AlterField(
            model_name='node',
            name='left_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Left node distance'),
        ),
        migrations.AlterField(
            model_name='node',
            name='right_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Right node distance'),
        ),
        migrations.AlterField(
            model_name='node',
            name='up_node_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Up node distance'),
        ),
    ]
