# Generated by Django 3.1.5 on 2021-02-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20210225_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
